### ISSUE TITLE
Crash after unblockchatinput()

### ISSUE THREAD

**Issue by shindi88** [paul-phoenix/SAMP-UDF-for-AutoHotKey#4]
Hey,
i get always a crash after the Anti-Spam function release the blockchatinput(). 

blockChatInput() {
if(!checkHandles())
return false
 
VarSetCapacity(nop, 2, 0)
 
dwFunc := dwSAMP + FUNC_SAMP_SENDSAY
NumPut(0x04C2,nop,0,"Short")
writeRaw(hGTA, dwFunc, &nop, 2)
 
dwFunc := dwSAMP + FUNC_SAMP_SENDCMD
writeRaw(hGTA, dwFunc, &nop, 2)
 
return true
}
 
; call this func to unblock chat messages to server
unBlockChatInput() {
if(!checkHandles())
return false
 
VarSetCapacity(nop, 2, 0)
 
dwFunc := dwSAMP + FUNC_SAMP_SENDSAY
NumPut(0xA164,nop,0,"Short")
writeRaw(hGTA, dwFunc, &nop, 2)
 
dwFunc := dwSAMP + FUNC_SAMP_SENDCMD
writeRaw(hGTA, dwFunc, &nop, 2)
 
return true
}

IfInString, A_LoopReadLine, Unterlasse das Spammen
{
BlockChatInput()
AddChatMessage("• {A9D0F5}[Keybinder] {FFFFFF} Für 2 Sekunden blockiert.")
Sleep, 2000
AddChatMessage("• {A9D0F5}[Keybinder] {FFFFFF} Wieder freigegeben.")
unBlockChatInput()
}

Deutsch:
Hallo,
Ich bekomme immer nach der unblockchatinput() Funktion einen SAMP Crash. Kann mir jemand helfen ?

LG

**Comment by paul-phoenix** [comment]
This function never fail for me.
