### ISSUE TITLE
readChat()

### ISSUE THREAD

**Issue by inv0ke** [paul-phoenix/SAMP-UDF-for-AutoHotKey#7]
There used to be a function for reading lines in the chat, in an older version that I can't find.

Could someone please rewrite and readd the function to readChat()?

Uses are things like: If someone offers you to purchase, or buy something.

var := readChat();
IfInString, var, "John Doe has offered you a service for $1, type /accept"
{
SendInPut, t/accept{enter}
Return
}

Or similar :)

edit: It was called "GetChatLine" in GTA API
GetChatLine_func := DllCall("GetProcAddress", UInt, hModule, Str, "GetChatLine")

**Comment by inv0ke** [comment]
Also if getTargetPed() could be readded too, that'd be awesome

**Comment by inv0ke** [comment]
...also getIdByPed(dwPed)

**Comment by Suchty112** [comment]
look the other SAMP-UDF here at Github :) Not this on my profil the other one.
